<!DOCTYPE html>
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> 
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
      .panel-body { 
    float: none; 
    width: 100%;
        background-color: #fff;
    padding: 17px;
}
  </style>
</head>
<body>

<div class="container" style="margin-top:70px;">
  <h2>Privacy Policy:</h2>
    
    
    
<p>ZUMILY LLC. PRIVACY STATEMENT</p>
<p><strong>PRIVACY STATEMENT</strong></p>
<p><strong>Effective Date: August 10, 2017</strong></p>
<p>This Privacy Statement (&ldquo;<strong>Privacy Statement</strong>&rdquo;) explains how Zumily LLC (&ldquo;<strong>Zumily</strong>,&rdquo; &ldquo;<strong>us</strong>,&rdquo; &ldquo;<strong>our</strong>,&rdquo; and &ldquo;<strong>we</strong>&rdquo;) uses your information and applies to all who use our website &ndash; www.Zumily.com, mobile applications, touch technologies, electronic services, social networking sites, interactive features, online services &ndash; or any of our described online activities we own or control, including any online activities owned, controlled, or operated by Zumily Affiliates, (collectively, the &ldquo;<strong>Site</strong>&rdquo;). In addition, please review the Site&rsquo;s <a href="http://www.zumily.com/legal/termsofservice"><strong>Terms of Use</strong></a> which governs your use of the Service, and includes, among other things, grants of rights from you, limits on our liability and your remedies, mandatory arbitration, and waiver of jury trial and class actions. <strong>By using our Site, you agree to our Terms of Service and consent to our collection, use and sharing of your information and data, and other activities, as described below.</strong></p>
<p><strong>By using the Site, you agree to the terms of this Privacy Statement. If you do not agree with the practices described in this Privacy Statement, please do not provide us with your personal information or interact with the Site.</strong></p>
<p>We may modify this Privacy Statement at any time. If we make any material changes, we will notify you by email (sent to the email address specified in your account) or by means of notice on the Site prior to the change becoming effective. You can determine when this Privacy Statement was last revised by referring to the "Effective Date&rdquo; above. You can review the last version of this Privacy Statement <a href="https://localhost/project/zumilyschool/pages/privacy1312017">here</a>.</p>
<p>This Privacy Statement is organized as follows:</p>
<p>1. <a href="https://localhost/project/zumilyschool/privacy-policy#Item1"><strong>Types of Information We Collect</strong></a></p>
<p>2. <a href="https://localhost/project/zumilyschool/privacy-policy#Item2"><strong>Your Choices</strong></a></p>
<p>3. <a href="https://localhost/project/zumilyschool/privacy-policy#Item3"><strong>How Zumily Uses Information</strong></a></p>
<p>4. <a href="https://localhost/project/zumilyschool/privacy-policy#Item4"><strong>When and Why Zumily Discloses Personal Information</strong></a></p>
<p>5. <a href="https://localhost/project/zumilyschool/privacy-policy#Item5"><strong>How Zumily Collects Information</strong></a></p>
<p>6. <a href="https://localhost/project/zumilyschool/privacy-policy#Item6"><strong>Security of Personal Information</strong></a></p>
<p>7. <a href="https://localhost/project/zumilyschool/privacy-policy#Item7"><strong>Accessing and Correcting Personal Information</strong></a></p>
<p>8. <a href="https://localhost/project/zumilyschool/privacy-policy#Item8"><strong>Social Networks</strong></a></p>
<p>9. <a href="https://localhost/project/zumilyschool/privacy-policy#Item9"><strong>Privacy Practices of Third Parties</strong></a></p>
<p>10. <a href="https://localhost/project/zumilyschool/privacy-policy#item10"><strong>Business Transfers and Corporate Changes</strong></a></p>
<p>11. <a href="https://localhost/project/zumilyschool/privacy-policy#Item11"><strong>Notice to Residents of Countries outside the United States of America</strong></a></p>
<p>12. <a href="https://localhost/project/zumilyschool/privacy-policy#Item12"><strong>Children&rsquo;s Privacy</strong></a></p>
<p>13. <a href="https://localhost/project/zumilyschool/privacy-policy#Item13"><strong>Contact Us; California Privacy Rights and Other Countries</strong></a></p>
<p>14. <a href="https://localhost/project/zumilyschool/privacy-policy#Item14"><strong>Glossary of Terms</strong></a></p>
<p>&nbsp;</p>
<p id="Item1"><strong>1. Types of Information We Collect</strong></p>
<p>We will collect information, including <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> and <a href="https://localhost/project/zumilyschool/privacy#Information">Non-Identifying Information</a>, when you interact with us and the Site, for example when you:</p>
<ol>
<li>register, subscribe, or create an account with Zumily;</li>
<li>access or use the Site;</li>
<li>contact customer service or use other customer support tools;</li>
<li>open or respond to our e-mails;</li>
<li>refer friends, family, or others to Zumily;</li>
<li>provide information to enroll or participate in <a href="https://localhost/project/zumilyschool/privacy#Programs">Other Programs</a> provided on behalf of, or together with, <a href="https://localhost/project/zumilyschool/privacy#Business">Business Partners</a>;</li>
<li>visit any page online that displays our ads or content;</li>
<li>connect or link to any Site via social networking sites;</li>
<li>post comments to <a href="https://localhost/project/zumilyschool/privacy#Communities">Online Communities</a>; and</li>
</ol>
<p>&nbsp;</p>
<p>This Privacy Statement does not apply to the collection of information in any way other than as listed above.</p>
<p id="Item2"><strong>2. Your Choices</strong></p>
<p>We think that you benefit from a more personalized experience when we know more about you and what you like. However, you can limit the information you provide to Zumily, and you can limit the communications that Zumily sends to you.</p>
<p><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; b) Device Data</strong></p>
<p>You may manage how your mobile device and mobile browser share certain <a href="https://localhost/project/zumilyschool/privacy#Device">Device Data</a> with Zumily, as well as how your mobile browser handles <a href="https://localhost/project/zumilyschool/privacy#Cookie">Cookies</a> by adjusting the privacy and security settings on your mobile device. Please refer to instructions provided by your mobile service provider or the manufacturer of your device to learn how to adjust your settings.</p>
<p>When you first visit or use the Site we may request permission to collect and use your device&rsquo;s precise geolocation. You can opt not to permit the collection of this information, or permit it only when using the mobile app, but it may limit certain functions or features of the Site. You can control how and whether we collect your precise geolocation information through your device&rsquo;s settings.</p>
<p><strong>a) Commercial E-mails</strong></p>
<p>You may choose not to receive commercial e-mails from us by following the instructions contained in any of the commercial e-mails we send or by logging into your account and adjusting your e-mail preferences. Please note that even if you unsubscribe from commercial email messages, we may still e-mail you non-commercial e-mails related to your account. You may update your subscription preferences at any time.</p>
<p id="Item3"><strong>3. How Zumily Uses Information</strong></p>
<p>We (or our <a href="https://www.groupon.com/privacy#Vendors">Vendors</a> on our behalf), use information collected as described in this Privacy Statement to:</p>
<ul>
<li>Operate, maintain and improve the Site and our services, and <a href="https://localhost/project/zumilyschool/privacy#Programs">Other Programs</a>;</li>
<li>Provide you with interest-based ads, push notifications, communications, and offers for products and services from us and participating <a href="https://localhost/project/zumilyschool/privacy#Business">Business Partners</a>, including based on your precise geolocation and favorite selection;</li>
<li>Answer your questions and respond to your requests;</li>
<li>Communicate and provide additional information that may be of interest to you about Zumily and our <a href="https://localhost/project/zumilyschool/privacy#Business">Business Partners</a>, sometimes by combining your information with information from <a href="https://localhost/project/zumilyschool/privacy#Other">Other Sources</a>;</li>
<li>To have the effective advertisement, we analyze our data to offers products or services that may be of interest to you;</li>
<li>Administer rewards, surveys, sweepstakes, contests, or other promotional activities or events sponsored by us or our <a href="https://localhost/project/zumilyschool/privacy#Business">Business Partners</a>;</li>
<li>Analyze our data and conduct consumer base research;</li>
<li>Manage our everyday business needs, such as administration of the Site, forum management, fulfillment, analytics, fraud prevention, and enforcement of our corporate reporting obligations and <a href="http://www.zumily.com/legal/termsofservice">Terms of Use</a>, or to comply with the law;</li>
<li>Send you reminders, technical notices, updates, security alerts, support and administrative messages, service bulletins, marketing messages, and requested information, including on behalf of <a href="https://localhost/project/zumilyschool/privacy#Business">Business Partners</a>;</li>
<li>We determine your interest based on the information we have about you directly or from <a href="https://localhost/project/zumilyschool/privacy#Other">Other Sources</a> to help us better understand you.</li>
<li>Also, we may use information collected as described in our Privacy Statement with your consent or as otherwise required or permitted by law.</li>
</ul>
<p>Zumily uses your geolocation, including your precise geolocation, consistent with this Privacy Statement as described in <a href="https://localhost/project/zumilyschool/privacy#item5">Section 5</a> below to deliver location-based offers, products or services that may be of interest to you.</p>
<p>If you use any features on the Site to send information about a product or service to another person (e.g., a friend, a colleague, a professional associate, etc.), we will also collect the <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> of that other person to the extent disclosed by you and may contact them using the information you provided us.</p>
<p id="Item4"><strong>4. When and Why Zumily Discloses Information</strong></p>
<p>We (or our <a href="https://localhost/project/zumilyschool/privacy#Vendors">Vendors</a> on our behalf) may share your <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> as required or permitted by law:</p>
<ul>
<li>with any Zumily <a href="https://localhost/project/zumilyschool/privacy#Affiliates">Affiliate</a> who may only use the <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> for the purposes described in this Privacy Statement;</li>
<li>with our <a href="https://localhost/project/zumilyschool/privacy#Vendors">Vendors</a> to provide services for us and who are required to protect the <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a>;
<ul>
<li>with relevant businesses or organizations.</li>
<li>with whom we have entered into an agreement that provides for the disclosure, sale, lease, or license of your Information;</li>
</ul>
</li>
<li>to comply with legal orders and government requests, or as needed to support auditing, compliance, and corporate governance functions;</li>
<li>to facilitate a direct relationship with you, including in connection with any program we administer on behalf of the <a href="https://localhost/project/zumilyschool/privacy#Business">Business Partner</a>;</li>
<li>to combat fraud or criminal activity, and to protect our rights or those of our <a href="https://localhost/project/zumilyschool/privacy#Affiliates">Affiliates</a>, users, and <a href="https://localhost/project/zumilyschool/privacy#Business">Business Partners</a>, or as part of legal proceedings affecting Zumily;</li>
<li>in response to a subpoena, or similar legal process, including to law enforcement agencies, regulators, and courts in the United States and other countries where we operate;</li>
<li>We encourage <a href="https://localhost/project/zumilyschool/privacy#Business">Business Partners</a> to adopt and post privacy policies. However, their use of <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> obtained through Zumily is governed by their privacy policies and is not subject to our control.</li>
</ul>
<p>We may also disclose <a href="https://localhost/project/zumilyschool/privacy#Information">Non-Identifiable Information</a>:</p>
<ul>
<li>for the same reasons we might share <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a>;</li>
<li>with our <a href="https://localhost/project/zumilyschool/privacy#Business">Business Partners</a> for their own analysis and research;</li>
<li>We do not share <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> with <a href="https://localhost/project/zumilyschool/privacy#ThirdParty">Third-Party Ad-Servers</a>; however, <a href="https://localhost/project/zumilyschool/privacy#ThirdParty">Third-Party Ad-Servers</a> may automatically collect <a href="https://localhost/project/zumilyschool/privacy#Information">Non-Identifying Information</a> about your visit to the Site and other websites, your device address, your Internet Service Provider and the browser you use to visit the Site. They do this by using <a href="https://localhost/project/zumilyschool/privacy#Cookie">Cookies</a>, clear gifs and other technologies. Information collected may be used, among other things, to deliver advertising targeted to your interests and to better understand the usage and visits to the Site and the other websites tracked by these third parties. This Privacy Statement does not cover the collection methods or use of the information collected by <a href="https://localhost/project/zumilyschool/privacy#ThirdParty">Third-Party Ad-Servers</a>, and Zumily is not responsible for <a href="https://www.groupon.com/privacy#Cookie">Cookies</a> or clear gifs in third party ads. We encourage you to review the privacy policies or statements of these third party advertising companies to learn more about their use of <a href="https://localhost/project/zumilyschool/privacy#Cookie">Cookies</a> and other technologies. If you would like more information about these practices and to know your choices about not having this information used by third party advertisers, please visit <a href="http://www.networkadvertising.org/">http://www.networkadvertising.org</a> and <a href="http://www.aboutads.info/choices/">http://www.aboutads.info/choices/</a>.</li>
</ul>
<p id="Item5"><strong>5. How Zumily Collects Information</strong></p>
<p>You provide us with your <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> when you register, subscribe, create an account, or otherwise when you provide us with your <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> during your interaction with the Site and <a href="https://localhost/project/zumilyschool/privacy#Programs">Other Programs</a>. We also collect <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> when you contact us online for customer service and other support using self-help tools, such as email, text, or by posting to an <a href="https://localhost/project/zumilyschool/privacy#Communities">Online Community</a>.</p>
<p>We also receive <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> and other online and offline information from <a href="https://localhost/project/zumilyschool/privacy#Other">Other Sources</a>. Zumily will use such information in accordance with applicable laws. Such information, when combined with Personal Information collected as provided in this Privacy Statement, will also be handled in accordance with this Privacy Statement. We also use cookies, tags, web beacons, local shared objects, files, tools and programs to keep records, store your preferences, improve our advertising, and collect <a href="https://localhost/project/zumilyschool/privacy#Information">Non-Identifying Information</a>, including <a href="https://localhost/project/zumilyschool/privacy#Device">Device Data</a> and information about your interaction with the Site and our <a href="https://localhost/project/zumilyschool/privacy#Business">Business Partners'</a> web sites.</p>
<p>We use <a href="https://localhost/project/zumilyschool/privacy#Cookie">Cookies</a> and <a href="https://localhost/project/zumilyschool/privacy#Device">Device Data</a> that allow us to connect your Site activity with other information we store about you in your profile or as related to your interactions with the Site. For more information on how Zumily uses <a href="https://localhost/project/zumilyschool/privacy#Cookie">Cookies</a>, including instructions on how to opt out of interest-based advertising, please review our <a href="http://www.zumily.com/cookie-policy">Cookies Policy</a>.</p>
<p><a href="https://www.groupon.com/privacy#Device">Device Data</a> may be collected automatically, and as soon as your device interacts with the Zumily, even if you are not logged into the Site using your device. If you have questions about the security and privacy settings of your mobile device, please refer to instructions from your mobile service provider or the manufacturer of your device to learn how to adjust your settings.</p>
<p>We collect your location information, including precise real-time geolocation, such as through look up based on IP address, GPS, Bluetooth, or WiFi signals, consistent with your choice of mobile device settings. We may also collect the precise location of your device when the app is running in the foreground, background, or even if you are not directly using the application depending on your device and its settings. Your device, as well as the Zumily mobile app, provides you with options to control how and when we collect your geolocation. You may be able to disallow our use of certain location data through your device or browser settings, for example, by disabling &ldquo;Location&rdquo; services for the Zumily application in iOS privacy settings.</p>
<p id="Item6"><strong>6. Security of Personal Information</strong></p>
<p>Zumily has implemented an information security program that contains administrative, technical and physical controls that are designed to safeguard <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a>. For example, we use industry-standard encryption technology to secure <a href="https://localhost/project/zumilyschool/privacy#Financial">Financial Account Information</a>. No method of transmission over the Internet, or method of electronic storage, is 100% secure, however. Therefore, we cannot guarantee its absolute security. If you have any questions about security on our Web site, you can contact us at privacy@Zumily.com.</p>
<p id="Item7"><strong>7. Accessing and Correcting Personal Information</strong></p>
<p>You can access, update and delete your <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> you provided to us, as described below, by managing this information through your online account or sending us an email at privacy@zumily.com. You can update or remove <a href="https://localhost/project/zumilyschool/privacy#Financial">Financial Account Information</a> as well. Keeping your <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> current helps ensure that we, our<a href="https://localhost/project/zumilyschool/privacy#Business"> Business Partners</a> offer you the offers that are most relevant to you.</p>
<p>If you want to deactivate your Zumily account or have other questions or requests, please contact us. While we are ready to assist you in managing your subscriptions, deactivating your account, and removing your active profile, we cannot always delete records of past interactions.</p>
<p>We will retain your <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> for as long as your account is active or as needed to provide you services. If you wish to deactivate your account or request that we no longer use your <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> to provide you services contact us at support@zumily.com. We will retain and use your <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements.</p>
<p id="Item8"><strong>8. Social Networks</strong></p>
<p><strong>Social Community Areas</strong></p>
<p>The Site may be accessible through or contain connections to areas where you may be able to publicly post information, communicate with others such as discussion boards or blogs, review products and merchants, and submit media content. Prior to posting in these areas, please read our <a href="http://www.zumily.com/legal/termsofservice">Terms of Use</a> carefully. All the information you post may be accessible to anyone with Internet access, and any <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> you include in your posting may be read, collected, and used by others. We recommend that you do not post any <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> in the social community areas.</p>
<p><strong>Social Networks</strong></p>
<p>You may log in to the Site using certain social network credentials. To manage the sharing of certain <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> with us when you connect with us through social networking platforms or applications, refer to the privacy policy and settings of the social networking website or application.</p>
<p>You also have the option to link social networks, such as Facebook, to your Zumily account. Once you register with Zumily and connect with the social network, you will be able to automatically post recent Zumily activity back to your social network.</p>
<p>By proceeding through any of the above steps, you grant Zumily permission to access all of the elements of your social network profile information that you have made available to be shared and to use it in accordance with the social network&rsquo;s terms of use and this Privacy Statement.</p>
<p id="Item9"><strong>9. Privacy Practices of Third Parties</strong></p>
<p>This Privacy Statement only addresses the use and disclosure of information by Zumily through your interaction with the Site. Other websites that may be accessible through links from the Site and <a href="https://localhost/project/zumilyschool/privacy#Programs">Other Programs</a> may have their own privacy statements and personal information collection, use, and disclosure practices. Our <a href="https://localhost/project/zumilyschool/privacy#Business">Business Partners</a> may also have their own privacy statements. We encourage you to familiarize yourself with the privacy statements provided by these other parties prior to providing them with information or taking advantage of a sponsored offer or promotion.</p>
<p id="Item10"><strong>10. Business Transfers and Corporate Changes</strong></p>
<p>Zumily and our <a href="https://localhost/project/zumilyschool/privacy#Affiliates">Affiliates</a> reserve the right to disclose, transfer, or license any and all information related to the Site, including <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a>:</p>
<ol>
<li>to a subsequent owner, co-owner or operator of one or more of the Sites or any portion or operation related to part of one or more of the Sites; or</li>
<li>in connection with a corporate merger, consolidation, or restructuring, the sale of all of our stock and/or assets, or other corporate change, including, without limitation, during the course of any due diligence process.</li>
</ol>
<p>&nbsp;</p>
<p id="Item11"><strong>11. Notice to Residents of Countries outside the United States of America</strong></p>
<p>If you live outside the United States (including in the European Economic Area (&ldquo;<strong>EE</strong>&rdquo;) and Switzerland (&ldquo;<strong>CH</strong>&rdquo;) collectively the &ldquo;<strong>EEA/CH</strong>&rdquo;), and you use the Site or provide us with <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> directly via the Site, your information will be handled in accordance with this Privacy Statement. By using the Site or giving us your <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a>, you are directly transferring your <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> and <a href="https://localhost/project/zumilyschool/privacy#Information">Non-Identifiable Information</a> to us in the United States. You agree and consent to our collection, transfer, and processing of your <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a> and <a href="https://localhost/project/zumilyschool/privacy#Information">Non-Identifiable Information</a> in accordance with this Privacy Statement. You are solely responsible for compliance with any data protection or privacy obligations in your jurisdiction when you use the Site or provide us with <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a>. Regardless of where we transfer your information, we still protect your information in the manner described in this Privacy Statement.</p>
<p id="Item12"><strong>12. Children&rsquo;s Privacy</strong></p>
<p>The Site is a general audience site not directed at children under the age of 13.</p>
<p>By using Zumily, you represent that you are at least eighteen years old and understand that you must be at least eighteen years old in order to create an account. We will promptly delete information associated with any account we obtain actual knowledge is associated with a registered user who is not at least eighteen years old.</p>
<p id="Item13"><strong>13. Contact Us; California Privacy Rights and Other Countries</strong></p>
<p>Please contact us if you have any questions or comments about our privacy practices or this Privacy Statement. You can reach us online at privacy@zumily.com. You can reach us via postal mail at the following address:</p>
<p>Zumily LLC</p>
<p>Attention: Privacy Office</p>
<p><strong>19504 Kilfinan St,</strong></p>
<p><strong>Porter Ranch, CA 91326</strong></p>
<p><strong>&nbsp;</strong></p>
<p>Zumily utilizes various valid data transfer mechanisms for Personal Information at its sole discretion in accordance with applicable data protection and privacy laws. We will continue to monitor and assess the appropriateness of other valid data transfer mechanisms as they become available.</p>
<p>Pursuant to Section 1798.83 of the California Civil Code, residents of California can obtain certain information about the types of personal information that companies with whom they have an established business relationship have shared with third parties for those third parties&rsquo; direct marketing purposes during the preceding calendar year. In particular, the law provides that companies must inform consumers about the categories of personal information that have been shared with third parties, the names and addresses of those third parties, and examples of the types of services or products marketed by those third parties. To request a copy of the information disclosure provided by Zumily pursuant to Section 1798.83 of the California Civil Code, please contact us via the email or address stated above. Please allow 30 days for a response.</p>
<p>If you are a California resident under the age of 18, and a registered user of any site where this policy is posted, California Business and Professions Code Section 22581 permits you to request and obtain removal of content or information you have publicly posted. To make such a request, please send an email with a detailed description of the specific content or information to privacy@zumily.com. Please be aware that such a request does not ensure complete or comprehensive removal of the content or information you have posted and that there may be circumstances in which the law does not require or allow removal even if requested.</p>
<p id="Item14"><strong>14. Glossary of Terms</strong></p>
<p><strong>Affiliate</strong> means an entity owned, directly or indirectly, by Zumily LLC or that is controlled by or under common control with Zumily LLC, and also includes joint ventures entered into by Zumily LLC and/or its Affiliates. References in this Privacy Statement to &ldquo;Zumily,&rdquo; &ldquo;we,&rdquo; or &ldquo;us&rdquo; also apply to Affiliates.</p>
<p><strong>Business Partners</strong> means, collectively, third parties with whom we conduct business, such as merchants, co-marketers, non-profit organizations, schools, and other companies or organizations with whom Zumily enters into agreements to support its business and operations.</p>
<p><strong>Cookie</strong> means a unique identifier, usually made up of small bits of text or code. For more information, please read our <a href="http://www.zumily.com/cookie-policy">Cookies Policy</a>.</p>
<p><strong>Device Data</strong> means information concerning a device you use to access, use, or interact with the Site, such as operating system type or mobile device model, browser type, domain, and other system settings, the language your system uses and the country and time zone of your device, geolocation, including precise geolocation, unique device identifier or other device identifier, advertising identifier, mobile phone carrier identification, and device software platform and firmware information.</p>
<p><strong>Non-Identifiable Information</strong> means information that alone cannot identify you, including data from <a href="https://localhost/project/zumilyschool/privacy#Cookie">Cookies</a>, <a href="https://localhost/project/zumilyschool/privacy#Pixel">Pixel Tags and Web Beacons</a>, and <a href="https://localhost/project/zumilyschool/privacy#Device">Device Data</a>. Non-Identifiable Information may be derived from <a href="https://localhost/project/zumilyschool/privacy#Personal">Personal Information</a>.</p>
<p><strong>Online Communities</strong> means, collectively, our social networking pages or accounts, forums, bulletin boards, discussion groups, chat rooms or other methods of communication that may be offered on or linked through the Site.</p>
<p><strong>Other Programs</strong> means special programs, features and functionality on our Site or other co-branded websites with <a href="https://localhost/project/zumilyschool/privacy#Business">Business Partners</a> that we reasonably control and that have special use terms applicable to such special programs, features and functionality.</p>
<p><strong>Other Sources</strong> means sources of information that legally provide Zumily with your information, and which are outside the scope of this Privacy Statement at the time of collection.</p>
<p><strong>Personal Information</strong> means information about you that specifically identifies you or, when combined with other information we have, can be used to identify you. This includes the following types of information:</p>
<p>&middot; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>Contact Information</strong>: your name, postal addresses, email addresses, social networking website user account names, telephone numbers, or other addresses at which you are able to receive communications.</p>
<p>&middot; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Relationship Information</strong>: information you provide that enables us to determine lifestyle, interests, and activities, including location information related to your state/province, city, or neighborhood; areas of interest, the types of deals that interest you, information collected through your interactions with social networks, demographic information (e.g., birth date, age, gender); and information about friends who refer you or whom you have referred;</p>
<p>&middot; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Financial Information</strong>: information collected from you to administer your participation in optional services and programs, such as your payment card number, expiration date, and card verification number.</p>
<p><strong>Pixel Tags and Web Beacons</strong> mean tiny graphic images placed on website pages or in our emails that allow us to determine whether you have performed specific actions.</p>
<p><strong>Third-Party Ad-Servers</strong> means <a href="https://localhost/project/zumilyschool/privacy#Vendors">Vendors</a> and other third parties that provide the technology to place ads on websites and track ad performance.</p>
<p><strong>Vendors</strong> means, collectively, third parties that perform business operations on behalf of Zumily, such as transaction processing, billing, mailing, communications services (e-mail, direct mail, etc.), marketing, data processing and analytics, servicing, collections, ad management, or information technology services.</p>    
    
</div>
</body>
</html>
