<!DOCTYPE html>
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> 
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
      .panel-body { 
    float: none; 
    width: 100%;
        background-color: #fff;
    padding: 17px;
}
  </style>
</head>
<body>

<div class="container" style="margin-top:70px;">
  <h2>Terms of Use</h2> 
<p>By entering your email, logging into your account, or accepting notifications, you agree to receive notification emails from Zumily.com for new flyers.</p>
<p>Welcome to the Zumily.com (defined below). By using it, you are agreeing to these Terms of Use as defined below. Please read them carefully. If you have any questions, <a href="https://localhost/project/zumilyschool/contact-us">contact us here</a>.</p>
<p>These Terms of Use were last updated on Jul 1, 2018.</p>
<p>ACCEPTANCE OF TERMS OF USE</p>
<p>Zumily.com LLC. (&ldquo;<strong>Zumily.com</strong>&rdquo; "<strong>we</strong>" or &ldquo;<strong>us</strong>&rdquo; or &ldquo;<strong>our</strong>&rdquo;) owns and operates the website, www.Zumily.com, the mobile and touch versions and any sites we have now or in the future that reference these Terms of Use (collectively, "<strong>Site</strong>"). By (a) using the Site and Zumily.com&rsquo; services through the Site, (b) signing up for an account, you agree to these Terms of Use (defined below) and any additional terms applicable to certain programs in which you may elect to participate. You also agree to our Privacy Statement, incorporated herein by reference and located at <a  href="http://www.zumily.com/zumily-privacy-policy">http://www.Zumily.com/privacy</a> (<strong>"Privacy Statement"</strong>), and acknowledge that you will regularly visit the Terms of Use (defined below) to familiarize yourself with any updates. The Privacy Statement, together with these terms of use, and any other terms contained herein or incorporated herein by reference, are collectively referred to as the "<strong>Terms of Use</strong>." The term "using" also includes any person or entity that accesses or uses the Site with crawlers, robots, data mining, or extraction tools or any other functionality.</p>
<p>IF YOU DO NOT AGREE TO THESE TERMS OF USE, IMMEDIATELY STOP USING THE SITE AND DO NOT USE ANY ZUMILY.COM SERVICE, PARTICIPATE IN ANY PROGRAM OR SERVICE OFFERED THROUGH THE SITE.</p>
<p>PLEASE REVIEW THE FOLLOWING SECTIONS OF THESE TERMS OF USE CAREFULLY: (A) <strong>DISPUTE RESOLUTION/ARBITRATION AGREEMENT,</strong> INCLUDING THE <strong>CLASS ACTION WAIVER</strong> DESCRIBED THEREIN, (B) <strong>LIMITATION OF LIABILITY,</strong> AND (C) <strong>INDEMNIFICATION/RELEASE.</strong></p>
<p>These Terms of Use are organized as follows:</p>
<p>1. <a href="https://localhost/project/zumilyschool/terms-of-use#about-the-site">About the Site</a></p>
<p>2. <a href="https://localhost/project/zumilyschool/terms-of-use#ownership-of-the-site">Ownership of the Site</a></p>
<p>3. <a href="https://localhost/project/zumilyschool/terms-of-use#access-to-the-site">Access to the Site</a></p>
<p>4. <a href="https://localhost/project/zumilyschool/terms-of-use#use-of-the-site">Use of the Site</a></p>
<p>5. <a href="https://localhost/project/zumilyschool/terms-of-use#modification">Modification</a></p>
<p>6. <a href="https://localhost/project/zumilyschool/terms-of-use#your-account">Your Account</a></p>
<p>7. <a href="https://localhost/project/zumilyschool/terms-of-use#your-conduct">Your Conduct</a></p>
<p>8. <a href="https://localhost/project/zumilyschool/terms-of-use#your-privacy">Your Privacy</a></p>
<p>9. <a href="https://localhost/project/zumilyschool/terms-of-use#copyright-and-trademarks">Copyright and Trademarks</a></p>
<p>10. &nbsp;<a href="https://localhost/project/zumilyschool/terms-of-use#copyright-policy">Infringement Reporting Procedures and Digital Millennium Copyright Act (DMCA) Procedures</a></p>
<p>11. <a href="https://localhost/project/zumilyschool/terms-of-use#disclaimer-of-warranty">&nbsp;Disclaimer of Warranty</a></p>
<p>12. <a href="https://localhost/project/zumilyschool/terms-of-use#limitation-of-liability">&nbsp;Limitation of Liability</a></p>
<p>13. <a href="https://localhost/project/zumilyschool/terms-of-use#electronic-communications">&nbsp;Electronic Communications</a></p>
<p>14. <a href="https://localhost/project/zumilyschool/terms-of-use#indemnification-releases">&nbsp;Indemnification/Release</a></p>
<p>15. <a href="https://localhost/project/zumilyschool/terms-of-use#assignment">&nbsp;Assignment</a></p>
<p>16. <a href="https://localhost/project/zumilyschool/terms-of-use#entire-agreement">&nbsp;Entire Agreement</a></p>
<p>17. <a href="https://localhost/project/zumilyschool/terms-of-use#choice-of-law">&nbsp;Choice of Law</a></p>
<p>18. <a href="https://localhost/project/zumilyschool/terms-of-use#dispute-resolution">&nbsp;Dispute Resolution</a></p>
<p>19. <a href="https://localhost/project/zumilyschool/terms-of-use#additional-disclosures">&nbsp;Additional Disclosures</a></p>
<p id="about-the-site"  ><strong>1. About the Site</strong></p>
<p>The Site is a platform through which certain Businesses, Schools, or Non-profits organizations (&ldquo;<strong>Merchants</strong>&rdquo;) can...</p>
<p>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; list their flyers, &nbsp;</p>
<p>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; make available coupons, promotional codes.</p>
<p>c)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Run flash-sales for specific dates and times.</p>
<p>d)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Schools events or reminders.</p>
<p>e)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Run flash-sales for specific dates and times.</p>
<p>Merchant Offerings, events, reminders, other available programs and pricing on the Site may change at any time in Merchant&rsquo;s sole discretion, without notice for which Zumily.com has no control. Zumily is not agents of these Merchants.</p>
<p id="ownership-of-the-site"><strong>2. Ownership of the Site</strong></p>
<p>The Site, any content on the Site, and the infrastructure used to provide the Site are proprietary to us, our affiliates, Merchants, and other content providers. By using the Site and accepting these Terms of Use: (a) Zumily.com grants you a limited, personal, nontransferable, nonexclusive, revocable license to use the Site pursuant to these Terms of Use and to any additional terms and policies set forth by Zumily.com; and (b) you agree not to reproduce, distribute, create derivative works from, publicly display, publicly perform, license, products, or services obtained from or through the Site without the express permission of Zumily.com.</p>
<p id="access-to-the-site"><strong>3. Access to the Site</strong></p>
<p>Zumily.com retains the right, at our sole discretion, to deny service or use of the Site or an account to anyone at any time and for any reason. While we use reasonable efforts to keep the Site and your account accessible, the Site and/or your account may be unavailable from time to time. You understand and agree that there may be interruptions in service or events, site access, or access to your account due to circumstances both within our control (e.g., routine maintenance) and outside of our control.</p>
<p id="use-of-the-site"><strong>4. Use of the Site</strong></p>
<p>As a condition to use of the Site, you agree that:</p>
<p>1)&nbsp;&nbsp;&nbsp; You have reached the age of majority in the state or province in which you reside;</p>
<p>2)&nbsp;&nbsp;&nbsp; You are able to create a binding legal obligation;</p>
<p>3)&nbsp;&nbsp;&nbsp; You are not barred from receiving products or services under applicable law;</p>
<p>4)&nbsp;&nbsp;&nbsp; You will not attempt to use the Site with crawlers, robots, data mining, or extraction tools or any other functionality;</p>
<p>5)&nbsp;&nbsp;&nbsp; Your use of the Site will at all times comply with these Terms of Use;</p>
<p>6)&nbsp;&nbsp;&nbsp; You have the right to provide any and all information you submit to the Site, and all such information is accurate, true, current, and complete;</p>
<p>7)&nbsp;&nbsp;&nbsp; You will update and correct information you have submitted to the Site and ensure that it is accurate at all times (out-of-date information will invalidate your account);</p>
<p>&nbsp;</p>
<p id="modification"><strong>5. Modification</strong></p>
<p>We reserve the right at all times to discontinue or modify any part of these Terms of Use in our sole discretion. If we make changes that affect your use of the Site or our services, we will post notice of the change on the Terms of Use page. Any changes to these Terms of Use will be effective upon our posting of the notice; provided that these changes will be prospective only and not retroactive. If you do not agree to the changes, you may close your account and you should not use the Site, or any services offered through the Site after the effective date of the changes. We suggest that you revisit our Terms of Use regularly to ensure that you stay informed of any changes. You agree that posting notice of any changes on the Terms of Use page is adequate notice to advise you of these changes, and that your continued use of the Site or our services will constitute acceptance of these changes and the Terms of Use as modified.</p>
<p id="your-account"><strong>6. Your Account</strong></p>
<p>You may only create and hold one account on the Site for your personal use. You are responsible for updating and correcting information you have submitted to create your account. You understand and agree that Zumily.com shall have no responsibility for any incident arising out of, or related to, your account settings. You must safeguard your password and supervise the use of your account. You are solely responsible for maintaining the security of your account and maintaining settings that reflect your preferences. We will assume that anyone using the Zumily.com through your account is you. You agree that you are solely responsible for any activity that occurs under your account.</p>
<p>We also reserve the right to change or discontinue any aspect or feature of our services or the Site, including, without limitation, requirements for use.</p>
<p id="your-conduct"><strong>7. Your Conduct</strong></p>
<p>All interactions on the Site must comply with these Terms of Use. To the extent your conduct, in our sole discretion, restricts or inhibits any other user from using or enjoying any part of the Site, we may limit or terminate your privileges on the Site and seek other remedies, including, without limitation, cancellation of your account.</p>
<p>The following activities are <strong><span style="text-decoration: underline;">prohibited</span></strong> on the Site and constitute violations of these Terms of Use:</p>
<p>1) &nbsp;&nbsp;&nbsp;&nbsp;Listing any content to the Site that:</p>
<p>i)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Contains viruses or malware;</p>
<p>ii)&nbsp;&nbsp;&nbsp; Offers unauthorized downloads of any copyrighted, confidential, or private information;</p>
<p>iii)&nbsp; Violates applicable laws (including, without limitation, intellectual property laws, laws relating to rights of privacy and rights of publicity, and laws related to defamation);</p>
<p>iv)&nbsp;&nbsp; Has the effect of impersonating others;</p>
<p>v)&nbsp;&nbsp;&nbsp; Is protected by copyright, trademark, or other proprietary right without the express permission of the owner of the copyright, trademark or other proprietary right.</p>
<p>2)&nbsp;&nbsp;&nbsp; Trying or actually doing any of the following:</p>
<p>i)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Scanning or testing the security or configuration of the Site or breaching security or authentication measures;</p>
<p>ii)&nbsp;&nbsp;&nbsp; Accessing data not intended for you, such as logging into a server or an account which you are not authorized to access;</p>
<p>iii)&nbsp; Hyperlinking to the Site from any other website without our initial and ongoing consent;</p>
<p>iv)&nbsp;&nbsp; Scanning or monitoring the Site for data gathering purposes in an effort to get listed flyers, coupons, events, or reminder information;</p>
<p>v)&nbsp;&nbsp;&nbsp; Interfering with service to any user in any manner, including, without limitation, by means of submitting a virus to the Site or attempting to overload, &ldquo;flood,&rdquo; &ldquo;spam,&rdquo; &ldquo;mail bomb,&rdquo; or &ldquo;crash&rdquo; the Site.</p>
<p>vi)&nbsp;&nbsp; Accessing, monitoring, or copying any content from the Site using any &ldquo;spider,&rdquo; &ldquo;robot,&rdquo; &ldquo;scraper,&rdquo; or other automated means or any manual process for any purpose without our express written permission;</p>
<p>vii) Tampering or interfering with the proper functioning of any part, page, or area of the Site or any functions or services provided by Zumily.com;</p>
<p id="your-privacy"><strong>8. Your Privacy</strong></p>
<p>We take the privacy of your Personal Information (defined in the Privacy Statement) seriously. We encourage you to carefully review our Privacy Statement for important disclosures about ways that we may collect, use, and share personal data and your choices. Our Privacy Statement is incorporated in and subject to these Terms of Use, and available <a href="http://www.zumily.com/privacypolicy">here</a>.</p>
<p id="copyright-and-trademarks"><strong>9. Copyright and Trademarks</strong></p>
<p>The Site contains copyrighted material, trademarks, and other proprietary information, including, without limitation, text, software, photos, video, graphics, music, and sound, and the entire contents of the Site are protected by copyright, trademark, and other intellectual property laws of the United States. Zumily.com owns a copyright in the selection, coordination, arrangement, and enhancement of such content, as well as in the content original to it. You may not modify, distribute, publish, transmit, publicly display, publicly perform, participate in the transfer or sale, create derivative works, or in any way exploit any of the content, in whole or in part. No downloading, copying, redistribution, retransmission, publication, or commercial exploitation of the content without the express permission of Zumily.com or the copyright owner is permitted. If downloading, copying, redistribution, retransmission, or publication of copyrighted material is permitted, you will make independent attribution and/or make no changes in or deletion of any author attribution, trademark legend, or copyright notice. You acknowledge that you do not acquire any ownership rights by downloading copyrighted material. Any violation of these restrictions may result in a copyright, trademark, or other intellectual property right infringement that may subject you to civil and/or criminal penalties.</p>
<p>Other marks on the site not owned by Zumily.com may be under license from the trademark owner thereof, in which case such license is for the exclusive benefit and use of Zumily.com unless otherwise stated or may be the property of their respective owners. You may not use Zumily.com's name, logos, trademarks or brands, or trademarks or brands of others on the Site without Zumily.com's express permission.</p>
<p id="copyright-policy"><strong>10. Infringement Reporting Procedures and Digital Millennium Copyright Act (DMCA) Procedures</strong></p>
<p>&middot; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Infringement Reporting Procedures. If you own copyright, trademark, patent, or other intellectual property rights (&ldquo;<strong>IP Rights Owner</strong>&rdquo;), or if you are an agent authorized to act on the IP Rights Owner&rsquo;s behalf (&ldquo;<strong>Authorized Agent</strong>&rdquo;), and you have a good faith belief that material or products on the Site infringe the IP Rights Owner&rsquo;s copyright, trademark, or other intellectual property right, and you would like to bring it to Zumily.com's attention, you can report your concern(s) by submitting your complaint <a href="https://localhost/project/zumilyschool/report_infringement">here</a>.</p>
<p>&middot; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DMCA Procedures. Zumily.com reserves the right to terminate your, or any third-party&rsquo;s, right to use the Site if such use infringes the copyrights of another. Zumily.com may, under appropriate circumstances and at its sole discretion, terminate your, or any third-party&rsquo;s, right to access to the Site, if Zumily.com determines that you are, or a third-party is, a repeat infringer. If you believe that any material has been posted via the Site by any third-party in a way that constitutes copyright infringement, and you would like to bring it to Zumily.com's attention, you must provide Zumily.co&ldquo;spider,&rdquo; m&rsquo;s DMCA Agent identified below with the following information:</p>
<ul>
<li>An electronic or physical signature of the person authorized to act on behalf of the owner of the copyrighted work.</li>
<li>An identification of the copyrighted work and the location on the Site of the infringing work.</li>
<li>A written statement that you have a good faith belief that the disputed use is not authorized by the owner, its agent, or the law.</li>
<li>Your name and contact information, including, without limitation, telephone number and email address.</li>
<li>A statement by you that the above information in your notice is accurate and, under penalty of perjury, that you are the copyright owner or authorized to act on the copyright owner&rsquo;s behalf.</li>
</ul>
<p>The contact information for Zumily.com&rsquo;s DMCA Agent for notice of claims of copyright infringement is: Zumily.com LLC. Attn: Copyright Agent, 19504 Kilfinan St, Porter Ranch, CA 91311, email: dmca@Zumily.com</p>
<p id="disclaimer-of-warranty"><strong>11. Disclaimer of Warranty</strong></p>
<p>AS PERMITTED BY APPLICABLE LAW, YOU EXPRESSLY AGREE THAT USE OF THE SITE IS AT YOUR SOLE RISK. NEITHER ZUMILY.COM, NOR ITS SUBSIDIARIES OR AFFILIATES OR ANY OF THEIR RESPECTIVE EMPLOYEES, AGENTS, MERCHANTS, THIRD-PARTY CONTENT PROVIDERS OR LICENSORS OR ANY OF THEIR OFFICERS, DIRECTORS, EMPLOYEES OR AGENTS, WARRANT THAT USE OF THE SITE WILL BE UNINTERRUPTED, SECURE, VIRUS-FREE, OR ERROR FREE, NOR DO THEY MAKE ANY WARRANTY AS TO</p>
<p>1. &nbsp;&nbsp;&nbsp;&nbsp;THE RESULTS THAT MAY BE OBTAINED FROM USE OF THE SITE, OR</p>
<p>2. &nbsp;&nbsp;&nbsp;&nbsp;THE ACCURACY, COMPLETENESS, OR RELIABILITY OF</p>
<p>i)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; THE CONTENT ON THE SITE, INCLUDING, WITHOUT LIMITATION, MERCHANT FLYERS, COUPONS, OR OTHER AVAILABLE PROGRAMS,</p>
<p>ii)&nbsp;&nbsp;&nbsp; MERCHANT OFFERINGS, PRODUCTS AND OTHER AVAILABLE PROGRAMS ACCESSIBLE OR AVAILABLE THROUGH THE SITE, ARE MADE ACCESSIBLE OR AVAILABLE ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS. TO THE EXTENT ALLOWED BY APPLICABLE LAW, ZUMILY.COM HEREBY DISCLAIMS ANY AND ALL REPRESENTATIONS, WARRANTIES, AND CONDITIONS, WHETHER EXPRESS, IMPLIED, OR STATUTORY, AS TO THE OPERATION OF THE SITE OR THE CONTENT, USER CONTENT, OR OTHER INFORMATION CONTAINED ON THE SITE OR THE MERCHANT OFFERINGS, PRODUCTS, OR OTHER AVAILABLE PROGRAMS ACCESSIBLE OR AVAILABLE THROUGH THE SITE, INCLUDING, WITHOUT LIMITATION, THOSE OF TITLE, NON-INFRINGEMENT, NON-INTERFERENCE, MERCHANTABILITY, SUITABILITY, AND FITNESS FOR A PARTICULAR PURPOSE, AS WELL AS WARRANTIES IMPLIED FROM A COURSE OF PERFORMANCE OR COURSE OF DEALING.</p>
<p id="limitation-of-liability"><strong>12. Limitation of Liability</strong></p>
<p>AS PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL ZUMILY.COM, ITS SUBSIDIARIES OR AFFILIATES OR ANY OF THEIR RESPECTIVE EMPLOYEES, OFFICERS, DIRECTORS, AGENTS, MERCHANTS, PARTNERS, THIRD-PARTY CONTENT PROVIDERS OR LICENSORS, OR ANY OF THEIR OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE FOR ANY DIRECT OR INDIRECT LOST PROFITS OR LOST BUSINESS DAMAGES, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF, RELATED TO, OR IN CONNECTION WITH ANY OF THE FOLLOWING: (</p>
<ol>
<li>YOUR INABILITY TO USE THE SITE;</li>
<li>YOUR USE OF THE SITE, THE CONTENT, USER CONTENT, INCLUDING, WITHOUT LIMITATION, ANY PERSONAL INFORMATION, AND ANY OTHER INFORMATION EITHER CONTAINED IN THE SITE OR SUBMITTED BY YOU TO THE SITE;</li>
<li>THE MERCHANT FLYERS, COUPONS, AND OTHER AVAILABLE PROGRAMS ACCESSIBLE OR AVAILABLE THROUGH THE SITE;</li>
<li>THE ORGANIZATION OR SCHOOLS EVENTS OR REMINDERS AVAILABLE THROUGH THE SITE;</li>
<li>MODIFICATION OR REMOVAL OF CONTENT SUBMITTED ON THE SITE;</li>
<li>THESE TERMS OF USE; OR</li>
<li>ANY IMPROPER USE OF INFORMATION YOU PROVIDE TO THE SITE, INCLUDING, WITHOUT LIMITATION, ANY PERSONAL INFORMATION. IN NO EVENT WILL ZUMILY.COM&rsquo;S LIABILITY IN CONNECTION WITH A MERCHANT OFFERING, PRODUCT, OR SERVICE. THE LIABILITY LIMITATIONS IN THIS SECTION ARE NOT INTENDED TO LIMIT ANY WARRANTY PROVIDED DIRECTLY BY A MERCHANT OR BY THE APPLICABLE MANUFACTURER OF PHYSICAL PRODUCTS OR ANY EXPRESS REPRESENTATIONS OR WARRANTIES BY ZUMILY.COM THAT ARE INCLUDED IN OTHER APPLICABLE TERMS, NOR ARE THEY INTENDED TO LIMIT REMEDIES YOU MIGHT HAVE FOR PRODUCT-RELATED INJURY.</li>
</ol>
<p id="electronic-communications"><strong>13. Electronic Communications</strong></p>
<p>When you use the Site or send emails to Zumily.com, you are communicating with us electronically and consent to receive electronic communications related to your use of the Site. We will communicate with you by email or by posting notices on the Site. You agree that all agreements, notices, disclosures, and other communications that are provided to you electronically satisfy any legal requirement that such communications be in writing. Notices from us will be considered delivered to you and effective when sent to the email address you provide on the Site or from which you otherwise email us.</p>
<p id="indemnification-releases"><strong>14. Indemnification/Release</strong></p>
<p>You agree to defend, indemnify, and hold harmless Zumily, its subsidiaries and affiliates, and their respective directors, officers, employees and agents from and against all claims and expenses, including, without limitation, attorneys&rsquo; fees, arising out of, related to, or in connection with any of the following:</p>
<p>a)&nbsp;&nbsp;&nbsp;&nbsp; any User Content submitted or posted by you, in connection with the Site, or any use of the Site in violation of these Terms of Use;</p>
<p>b)&nbsp;&nbsp;&nbsp;&nbsp; fraud you commit or your intentional misconduct or gross negligence; or</p>
<p>c)&nbsp;&nbsp;&nbsp;&nbsp; your violation of any applicable U.S., or foreign law or rights of a third-party.</p>
<p>&nbsp;</p>
<p>You are solely responsible for your interactions with businesses, organizations, and schools and you hereby release Zumily from any and all claims or liability related to any product or service of a businesses or organizations, regardless of whether such product or service available through the Site, any action or inaction by a Merchant, including, without limitation, but not limited to any harm caused to you by action or inaction of a Merchant, a Merchant&rsquo;s failure to comply with applicable law and/or failure to abide by the terms of a Merchant Offering or any other product or service purchased or obtained by you from the Merchant, and any conduct, speech or User Content, whether online or offline, of any other third-party.</p>
<p id="assignment"><strong>15. Assignment</strong></p>
<p>You may not assign these Terms of Use, or any rights, benefits, or obligations hereunder, by operation of law or otherwise, without the express written permission of Zumily. Any attempted assignment that does not comply with these Terms of Use shall be null and void. Zumily may assign these Terms of Use, in whole or in part, to any third-party in its sole discretion.</p>
<p id="entire-agreement"><strong>16. Entire Agreement</strong></p>
<p>The Terms of Use, including, without limitation, the incorporated Terms of Sale, Special Programs, Privacy Statement, and other terms incorporated by reference, constitute the entire agreement and understanding between you and Zumily with respect to the subject matter hereof and supersedes all prior or coexistent communications and proposals, whether oral or written, between you and Zumily with respect to such subject matter.</p>
<p id="choice-of-law"><strong>17. Choice of Law</strong></p>
<p>Any disputes arising out of or related to these Terms of Use and/or any use by you of the Site or Zumily&rsquo;s services shall be governed by the laws of the State of California, without regard to its choice of law rules and without regard to conflicts of laws principles.</p>
<p id="dispute-resolution"><strong>18. Dispute Resolution/Arbitration Agreement</strong></p>
<p><strong>(a) <span style="text-decoration: underline;">Binding Arbitration</span>. Except as specifically stated herein, any dispute or claim between you and Zumily and/or its subsidiaries, affiliates, and/or any of their respective members, officers, directors, and employees (all such entities collectively referred to herein as the &ldquo;Zumily Entities&rdquo;) arising out of, relating in any way to, or in connection with the Terms of Use, the Site or your use of the Site, your Personal Information, or any Products or Merchant Offerings (&ldquo;Dispute(s)&rdquo;) shall be resolved exclusively by final, binding arbitration; except that you may bring a qualifying claim over a Dispute in a small claims court. By virtue of this Dispute Agreement (defined below), you and Zumily are each giving up the right to go to court and have a Dispute heard by a judge or jury (except as otherwise set forth in this Section 24(a) or Section 24(d)).</strong> The provisions of this Section 24 shall constitute your and Zumily&rsquo;s written agreement to arbitrate Disputes under the Federal Arbitration Act (&ldquo;<strong>Dispute Agreement</strong>&rdquo;). The arbitration will be administered by the American Arbitration Association (&ldquo;<strong>AAA</strong>&rdquo;) and conducted before a single arbitrator pursuant to its rules, including, without limitation, the AAA&rsquo;s Consumer-Arbitration Rules, available at <a href="https://www.adr.org/consumer">https://www.adr.org/consumer</a>. The arbitrator will apply and be bound by this Agreement, apply applicable law and the facts, and issue a reasoned award, if appropriate.</p>
<p>To begin an arbitration proceeding, you must submit the Dispute by utilizing the forms available at <a href="https://www.adr.org/consumer">https://www.adr.org/consumer</a>, and simultaneously sending a copy of the completed form to the following address: Zumily LLC, 19504 Kilfinan St, Porter Ranch CA 91326. Payment of all filing, administration, and arbitrator fees will be governed by the AAA's rules. Zumily will reimburse those fees for Disputes totaling less than $10,000 unless the arbitrator determines the Dispute is frivolous. Likewise, Zumily will not seek attorneys' fees and costs in arbitration unless the arbitrator determines the Dispute is frivolous. The arbitration will be conducted based upon written submissions unless you request, and/or the arbitrator determines, that a telephone or in-person hearing is necessary. In addition, you hereby unconditionally agree that</p>
<p>a)&nbsp;&nbsp;&nbsp;&nbsp; the arbitrator shall apply California law consistent with the FAA and applicable statutes of limitations, and shall honor claims of privilege recognized at law; and</p>
<p>b)&nbsp;&nbsp;&nbsp;&nbsp; the arbitrator&rsquo;s decision shall be controlled by these Terms of Use and any of the other agreements referenced herein that you may have entered into in connection with the Site;</p>
<p>c)&nbsp;&nbsp;&nbsp;&nbsp; in the event the AAA is unavailable or unwilling to hear the Dispute, you and the applicable Zumily Entity(ies) shall agree to, or a court shall select, another arbitration provider.</p>
<p>&nbsp;</p>
<p><strong>(b) <span style="text-decoration: underline;">No Class Action Matters</span>. We each agree that we shall bring any Dispute against the other in our respective individual capacities and not as a plaintiff or class member in any class, representative proceeding or as an association. In addition, we each agree that Disputes shall be arbitrated only on an individual basis and not in a class, consolidated, or representative action and that the arbitrator may award relief (including injunctive relief) only on an individual basis. The arbitrator does not have the power to vary these provisions.</strong></p>
<p><strong>(c) <span style="text-decoration: underline;">Choice of Law and Forum; No Jury Trial</span></strong>. If for any reason a Dispute proceeds in court: (i) except with respect to a qualifying claim over a Dispute in a small claims court, which you shall have the right to bring in a court of competent jurisdiction in the county in which you reside, you and Zumily agree that any Dispute may only be instituted in a state or federal court in LA County, California; (ii) you and Zumily irrevocably consent and submit to the exclusive personal jurisdiction and venue of such courts for resolution of such Disputes; and (iii) you and Zumily agree to waive any right to a trial by jury. You and Zumily agree that the Federal Arbitration Act, the AAA rules, applicable federal law, and the laws of the State of California, without regard to principles of conflicts of law, will govern this Dispute Agreement and any Disputes.</p>
<p><strong>(d) <span style="text-decoration: underline;">Severability</span></strong>. With the exception of Section 24(b) above, if any part of this Section 24 is ruled to be unenforceable, then the balance of this Section 24 shall remain in full effect and construed and enforced as if the portion ruled unenforceable were not contained herein. If Section 24(b) above is ruled to be unenforceable, then Section 24(a) shall be deemed unenforceable, but the rest of Section 24 shall remain in full effect.</p>
<p><strong>(e) <span style="text-decoration: underline;">Injunctive Relief</span></strong>. Notwithstanding anything to the contrary in this Dispute Agreement, either party may bring suit in court seeking an injunction or other equitable relief arising out of or relating to the infringement of a party&rsquo;s intellectual property, or any illegal or intentional act affecting the accessibility, functionality, or the security of the Site, and/or any illegal or intentional act against your interests or the general business interests of Zumily.</p>
<p id="additional-disclosures"><strong>19. Additional Disclosures</strong></p>
<p>No waiver by either you or Zumily of any breach or default or failure to exercise any right allowed under these Terms of Use is a waiver of any preceding or subsequent breach or default or a waiver or forfeiture of any similar or future rights under our Terms of Use. The section headings used herein are for convenience only and shall be of no legal force or effect. If a court of competent jurisdiction holds any provision of our Terms of Use invalid, such invalidity shall not affect the enforceability of any other provisions contained in these Terms of Use, and the remaining portions of our Terms of Use shall continue in full force and effect.</p>
<p>If you are a California resident, you may report complaints to the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs by contacting them in writing at 1625 North Market Blvd., Suite N-112, Sacramento, California 95834, or by telephone at (800) 952-5210.</p>
<p>You are contracting with Zumily LLC. Correspondence should be directed to: Zumily LLC, 19504 Kilfinan St, Porter Ranch, CA 91326.</p>
<p>The provisions of these Terms of Use apply equally to, and are for the benefit of, Zumily, its subsidiaries, affiliates, Merchants, and its third-party content providers and licensors, and each shall have the right to assert and enforce such provisions directly</p>
 
    
</div>
</body>
</html>
